#! /bin/bash

if ! command -v yay; then
    sudo pacman -Syu git base-devel man
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -si
    cd ..
fi

yay --noconfirm -Syu \
    neovim zsh stow ripgrep fzf curl tmux openssh\
    ttf-cascadia-mono-nerd ttf-jetbrains-mono-nerd \
    go nodejs npm php composer\
    brave-bin spotify-launcher obsidian \
    spotify-tui \

bash ./install/helpers/stow-basics
bash ./install/helpers/hypr-setup
stow hypr
