#! /bin/bash

sudo apt update
sudo apt upgrade -y
sudo apt install -y git zsh stow ripgrep fzf curl tmux i3 rofi

# Install Docker
sudo apt install ca-certificates gnupg curl
sudo mkdir -p /etc/apt/keyrings
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
echo \
         "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
         "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
         sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Install neovim prereqs
sudo apt install -y ninja-build gettext cmake unzip curl python3-pip
git clone https://github.com/adi1090x/rofi.git

./install/helpers/install-nvm-source
./install/helpers/install-neovim-source
./install/helpers/install-nerdfont-source
stow i3
