#!/bin/bash

yay -S --noconfirm \
    linux-headers nvidia-dkms nvidia-utils egl-wayland xdg-desktop-portal-hyprland\
    hyprland rofi-wayland waybar hyprpaper wayland ly mako pywal \
    grim slurp wl-clipboard wf-recorder grimblast flameshot

sudo systemctl enable ly

script_dir = $(cd -- "$( dirname -- "{BASH_SOURCE[0]}" )" &> /dev/null && pwd)
cd ../../hypr/rofi/
chmod +x setup.sh
./setup.sh

# The rest of this is for Nvidia support
if ! grep -q "nvidia_drm.modeset=1" /boot/loader/entries/; then
    for FILE in $(grep -l "options .*" /boot/loader/entries/* --exclude=\*-fallback\*); do
        sed -iE 's/options (.*)/options \1 nvidia_drm.modeset=1 nvidia_drm.fbdev=1/' $FILE
    done
fi

if ! grep -q "GBM_BACKEND" /etc/profile; then
    echo "export GBM_BACKEND=nvidia-drm" | sudo tee -a /etc/profile
    echo "export __GLX_VENDOR_LIBRARY_NAME=nvidia" | sudo tee -a /etc/profile
fi

MODULE_FILE=/etc/mkinitcpio.conf
if ! grep -q "nvidia" $MODULE_FILE; then
    sudo cp $MODULE_FILE $MODULE_FILE.bak
    sudo sed -i -r -e 's/MODULES=\((.*)\)/MODULES=\(\1 nvidia nvidia_modeset nvidia_uvm nvidia_drm\)/' $MODULE_FILE 
    sudo mkinitcpio -P
fi

git clone https://github.com/GideonWolfe/Zathura-Pywal && ./Zathura-Pywal/install.sh && rm -rf Zathura-Pywal
